apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-client
#  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products-client
  template:
    metadata:
      labels:
        app: products-client
    spec:
      containers:
        - image: docker.io/rathidockerrepo/products-angular-image:latest
          name: products-client
          imagePullPolicy: Always
          env:
            - name: API_KEY
              value: 'http://192.168.99.103:30833'
#          ports:
#            - containerPort: 4200
